name: Haskell CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up GHC
      uses: haskell/actions/setup@v2
      with:
        ghc-version: '9.6.7'
        cabal-version: '3.10.1.0'

    - name: Cache
      uses: actions/cache@v3
      with:
        path: |
          ~/.cabal/store
          dist-newstyle
          .cabal-sandbox/
        key: ${{ runner.os }}-${{ hashFiles('**/*.cabal', 'cabal.project') }}

    - name: Install dependencies
      run: |
        cabal update
        cabal build --only-dependencies --enable-tests

    - name: Build
      run: cabal build --enable-tests

    - name: Run tests
      run: cabal test --test-show-details=direct

    - name: Check formatting
      run: |
        cabal install fourmolu
        find . -name '*.hs' -exec fourmolu -m check {} +
